### ISSUE TITLE
PAGE_FAULT_IN_NONPAGED_AREA when ManualMapping

### ISSUE THREAD

**Issue by kreapbuddy** [btbd/wpp#2]
Hello, i can use this project with sc create load without any problem. But if i manual map this with your project  [https://github.com/btbd/umap](url), i get PAGE_FAULT_IN_NONPAGED_AREA.

Minidump Call Stack:
![image](https://user-images.githubusercontent.com/19592176/84626214-64cf2280-aeed-11ea-877a-9fbb27d14d74.png)

IDA:
![image](https://user-images.githubusercontent.com/19592176/84626379-a8299100-aeed-11ea-9a2b-aa87b49cfd09.png)
![image](https://user-images.githubusercontent.com/19592176/84626408-b2e42600-aeed-11ea-9c63-d262a3907bd4.png)

Probably exception line:
![image](https://user-images.githubusercontent.com/19592176/84626474-cc856d80-aeed-11ea-989c-f4826da34f96.png)

**Comment by kreapbuddy** [comment]
I found the problem, its about
https://github.com/btbd/wpp/blob/d495b3a0351b908f9d9773c91ad674b216f89314/wpp/wpp.c#L10

So i replaced it to;
` wpps;`

then call this at entry:
`
RtlZeroMemory( &wpps, sizeof( wpps ) );
`

That's fixed my issue.

**Comment by btbd** [comment]
@kreapbuddy Which version of umap were you using? In the first version I forgot to increment the relocation pointer which would cause only the first relocation to be properly calculated (i.e. explaining the bad pointer deref). You shouldn't have that issue on the latest.
