### ISSUE TITLE
Issue with manual mapping

### ISSUE THREAD

**Issue by themasterpaster** [btbd/wpp#4]
I am using IoCreateDriver to create a driver object for the real driver entry from a fake entry point (so it's compatible with a manual mapper such as kdmapper, drvmap, etc) and then manual map the driver with kdmapper, the driver is loaded fine but the diskdrive serial stays the same. What could we do about this?

**Comment by btbd** [comment]
@themasterpaster [RtlCaptureStackBackTrace](https://github.com/btbd/wpp/blob/master/wpp/wpp.c#L44) will fail if not called from a valid module. You can either implement your own RtlCaptureStackBackTrace or do a hasty workaround like this:
```c
for (ULONG i = 0; i < wpps.Length; ++i) {
    PWPP wpp = &wpps.Buffer[i];
 
    PVOID *frame = _AddressOfReturnAddress();
    for (ULONG r = 1; r < 0x10; ++r) {
        if (frame[r] == wpp->ReturnAddress) {
            wpp->Filter(&context, wpp->ReturnAddress, frame, ((PVOID *)PsGetCurrentThreadStackBase()) - 1);
 
            break;
        }
    }
}
```
